const conf = require('../conf')

module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize
  const Companies = sequelize.define('companies', {
    companyId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
      _autoGenerated: true,
      defaultValue: Sequelize.literal('DEFAULT'),
    },
    fullName: {
      type: DataTypes.STRING(150),
      allowNull: false,
      validate: { len: [10, 150] },
    },
    shortName: {
      type: DataTypes.STRING(100),
      validate: { len: [5, 100] },
    },
    logoUrl: {
      type: DataTypes.STRING(300),
      validate: { isUrl: true },
    },
    identificationNumber: {
      type: DataTypes.DOUBLE,
    },
  }, {
    tableName: 'companies',
    underscored: true,
    timestamps: false,
    schema: conf.get('DATABASE_SCHEMA'),
  })

  return Companies
}
