const conf = require('../conf')

module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize
  const CurrenciesQuotes = sequelize.define('currenciesQuotes', {
    currencyQuoteId: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      allowNull: false,
      _autoGenerated: true,
      defaultValue: Sequelize.literal('DEFAULT'),
      field: 'currency_base_usd_quote_id',
    },
    quotation: {
      type: DataTypes.DOUBLE,
      allowNull: false,
      validate: { notEmpty: true, isDecimal: true },
    },
    datetime: {
      type: DataTypes.DATE,
      allowNull: false,
    },
  }, {
    tableName: 'currencies_base_usd_quotes',
    underscored: true,
    timestamps: false,
    schema: conf.get('DATABASE_SCHEMA'),
  })

  CurrenciesQuotes.associate = (models) => {
    CurrenciesQuotes.belongsTo(models.currencies, {
      foreignKey: {
        name: 'currencyIdKey',
        field: 'currency_base_usd_id',
      },
      targetKey: 'currencyId',
      as: 'currency',
    })
  }

  return CurrenciesQuotes
}
