const conf = require('../conf')

module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize
  const Currencies = sequelize.define('currencies', {
    currencyId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
      _autoGenerated: true,
      defaultValue: Sequelize.literal('DEFAULT'),
    },
    code: {
      type: DataTypes.ENUM('RUB', 'EUR', 'USD'),
      allowNull: false,
      validate: { isIn: ['RUB', 'EUR', 'USD'] },
    },
    name: {
      type: DataTypes.STRING(50),
      validate: { len: [2, 50] },
    },
  }, {
    tableName: 'currencies_base_usd',
    underscored: true,
    timestamps: false,
    schema: conf.get('DATABASE_SCHEMA'),
  })

  Currencies.associate = (models) => {
    Currencies.hasMany(models.currenciesQuotes, {
      foreignKey: {
        name: 'currencyIdKey',
        field: 'currency_id',
      },
      as: 'currencyQuotes',
    })
  }

  return Currencies
}
